### ISSUE TITLE
Activate remote machines locally from mac

### ISSUE THREAD

**Issue by srid** [srid/nixos-config#23]
https://github.com/serokell/deploy-rs

Work on my primary machine (macOS) and remotely activate new configuration for Linux machines and such.

**Comment by srid** [comment]
or,

```
nix run nixpkgs#nixos-rebuild -- switch --fast --flake .#pinch --target-host root@pinch --build-host root@pinch
```

https://www.haskellforall.com/2023/01/announcing-nixos-rebuild-new-deployment.html

**Comment by srid** [comment]
This works for non-trivial configurations:

https://github.com/srid/nixos-config/blob/0196461adb922b294b64b33a4262ab66247636f4/justfile#L4-L9

But not when using certain packages, like nixvim:

https://nixos.zulipchat.com/#narrow/stream/413948-nixos/topic/NixOS.20tutorial.20series/near/422506285

**Comment by LovingMelody** [comment]
Per nixos-rebuild(8), you may wish to consider dropping "--fast"
```man
       --fast  Equivalent to --no-build-nix.  This  op‐
               tion is useful if you call nixos-rebuild
               frequently  (e.g. if you’re hacking on a
               NixOS module).
```

**Comment by srid** [comment]
Resolved in https://github.com/srid/nixos-flake/pull/54
