### ISSUE TITLE
ln: failed to create symbolic link '.../Applications/Home Manager Apps': Permission denied

### ISSUE THREAD

**Issue by ParetoOptimalDev** [srid/nixos-config#32]
With just 2130b83 when I try to use `nix develop -c , activate` I get the error:

```sh
Creating home file links in /Users/johnw
ln: failed to create symbolic link '/Users/.../Applications/Home Manager Apps': Permission denied
```

This seems related to an old but still active issue in home-manager where it conflicts with nix-darwin:

https://github.com/nix-community/home-manager/issues/1341

**Comment by ParetoOptimalDev** [comment]
Skimming that issue, it may be that I'm still on an older OSX version than you are if you aren't experiencing this issue.

**Comment by srid** [comment]
FWIW: on my macOS,

```
❯ sw_vers
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65

❯ ls -ld ~/Applications/Home\ Manager\ Apps
lrwxr-xr-x 93 srid  8 Mar 10:04 /Users/srid/Applications/Home Manager Apps -> /nix/store/d05ssz859zi0bbwra1ybniq21xs18vrm-home-manager-files/Applications/Home Manager Apps
```

**Comment by dansteeves68** [comment]
Using a nix darwin & home manager configuration with flakes, I also get this error:

`Creating home file links in /Users/dan
ln: failed to create symbolic link '/Users/dan/Applications/Home Manager Apps': Permission denied`

When I do `rm -rf ~/Applications` then redo the `darwin-rebuild switch` command it works.

**Comment by srid** [comment]
If anyone still see this, please try https://github.com/juspay/nixos-unified-template and if it happens there too, then open an issue in that rep.
