### ISSUE TITLE
factor out lib flake

### ISSUE THREAD

**Issue by edrex** [srid/nixos-config#33]
I'm reworking my config for flake-parts (https://github.com/edrex/nixos-config/tree/new-main) and I want to use your lib functions. Would you want to factor out a `flake-lib` flake with with versioned releases etc? I can co-maintain, or just send you PRs.

**Comment by srid** [comment]
I'm unable to access that repo; is it private?

Yea, I'm happy about refactoring the code in this repo to facilitate reuse. I was actually thinking of creating a Git template that people can use to bootstrap a skeleton that supports nixos/nix-darwin/home-manager and based on flake-parts. Perhaps that template repo's flake.nix can expose the `flake-lib`.

**Comment by edrex** [comment]
> I'm unable to access that repo; is it private?

Oops, fixed.  I archived and apparently also unpublished that repo a few months ago, and now I'm bringing it back (although I'm thinking to rename it to just "edrex/config", been iterating a lot on naming/repo hierarchy).

> [:#](https://github.com/srid/nixos-config/blob/master/lib.nix#L1) Support code for this repo. This module could be made its own external repo.

Yes, a `flake-lib` flake with [lib.nix](https://github.com/srid/nixos-config/blob/master/lib.nix) and a template ready-to-use template (with commented blocks that fully exercise the API, would be amazing.

I'd like to do code reviews on this, and work in feature branches. Maybe we start with an empty README and then do PRs from there?

**Comment by edrex** [comment]
(happy having it under your namespace cuz it's your code, just interested to improve my nix language skills, to maximize my utilization of this, and to support others through station-keeping.)

**Comment by srid** [comment]
Sure, I'll try to bootstrap something and let you know.

**Comment by srid** [comment]
@edrex Let's move the discussion to this repo, starting from this PR: https://github.com/srid/nixos-template/pull/1

**Comment by srid** [comment]
I've removed the WIP status on https://github.com/srid/nixos-flake - but still open to API changes/ improvements.
